name: Build Game
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7
      
      - name: Cache Windows Build Object Files
        uses: actions/cache@v4
        with:
          path: |
            export/release/windows/obj
            C:/Users/runneradmin/AppData/Local/hxcpp
            .haxecache
        # 프로젝트 폴더 내 파일이 바뀌어도 엔진(플릭셀) 라이브러리는 그대로이므로 
        # haxelib 장부 기준(Project.xml이나 유사 파일)으로 키를 생성해 고정합니다.
          key: ${{ runner.os }}-build-obj-${{ hashFiles('**/Project.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-obj-
    # 2. 오직 이 빌드 스텝 안에서만 캐시 환경 변수와 플래그가 작동하도록 묶기
      - name: Install Libraries
        run: |
          haxelib install lime 8.1.2
          haxelib install openfl 9.3.3
          haxelib install flixel 5.6.1
          haxelib install flixel-addons 3.2.2
          haxelib install flixel-ui 2.6.1
          haxelib install flixel-tools
          haxelib install hscript 1.1.3
          haxelib install hxdiscord_rpc 1.2.4
          haxelib install flxanimate
          haxelib install hxcpp
          haxelib install hscript-iris 1.1.3
          haxelib install tjson 1.4.0
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
      - name: Build Psych Engine
        env:
          HAXE_CACHE: .haxecache
          HAXE_COMPILER_CACHE: .haxecache
        run: |
          haxelib run lime build windows
      - name: Find hxcpp cache
        run: |
          echo "=== haxelib 경로 ==="
          haxelib config
          echo "=== hxcpp 찾기 ==="
          Get-ChildItem -Path C:\ -Recurse -Filter "hxcpp" -Directory -ErrorAction SilentlyContinue | Select-Object FullName
          Get-ChildItem -Path D:\ -Recurse -Filter "hxcpp" -Directory -ErrorAction SilentlyContinue | Select-Object FullName
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FNF-BattleCats-Build
          path: export/release/windows/bin
